name: Notify website of release
on:
  release:
    types: [published, edited, deleted]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rebuild
        env:
          DEPLOY_HOOK: ${{ https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/a432a173-afb1-4f56-bb5c-9a3e3c555a7d }}
        run: curl -fsS -X POST "$DEPLOY_HOOK"
